swagger: "2.0"
info:
  description: internal API for the Partnership on AI's AI Incident Database
  title: AIID API
  version: v1
schemes:
  - https
host: aiid-api-3eievfc5ca-uc.a.run.app
basePath: /
externalDocs:
  url: https://github.com/PartnershipOnAI/aiid
  description: GitHub Repository
produces:
  - application/json
consumes:
  - application/json
paths:
  /auth/login:
    post:
      description: log in using email and password
      parameters:
        - in: body
          name: data
          required: true
          schema:
            required: [email, password]
            properties:
              email:
                type: string
                example: user@example.com
              password:
                type: string
                example: password
      responses:
        200:
          description: authentication successful
          schema:
            required: [status, token, roles]
            properties:
              status:
                enum: [success]
                type: string
              token:
                type: string
                description: JSON web token used for authentication
                example: "abc.def.ghi"
              roles:
                type: array
                items:
                  type: string
                  enum: [public, partner, editor, admin]
        403:
          description: invalid password or email
          schema:
            required: [status, error]
            properties:
              status:
                type: string
                enum: [error]
              error:
                type: string
                example: Invalid password or email
  /reports/submit:
    parameters:
      - $ref: "#/parameters/authorization"
    post:
      description: Submit a report. the URL will be processed and inserted into the Algolia index and database.
      parameters:
        - in: body
          name: data
          required: true
          schema:
            required: [url]
            properties:
              url:
                type: string
                example: "https://example.com/articles/ai-news"
      responses:
        202:
          description: successfully processed document
        400:
          description: missing body or URL key
          schema:
            $ref: "#/responses/400"
responses:
  "400":
    description: invalid request
    schema:
      required: [status, error]
      properties:
        status:
          type: string
          enum: [error]
        error:
          type: string
          description: a description of the error
parameters:
  authorization:
    in: header
    name: Authorization
    schema:
      type: string
      example: "abc.def.ghi"
    description: token issued by the /auth/login endpoint
    required: true
